#' Perform FR dimensionality reduction on GNG and project cells to same space
#'
#' @param gng_out The object generated by [gng()]
#' @param x If desired, the original dimred can also be projected using a randomForest
#'
#' @importFrom dynutils scale_minmax
#' @importFrom stats predict na.omit
#' @importFrom igraph graph_from_data_frame layout_with_fr
#'
#' @export
project_gng <- function(gng_out, x = NULL) {
  # Project the nodes to a 2D plane
  igr <-
    gng_out$edges %>%
    select(.data$i, .data$j) %>%
    igraph::graph_from_data_frame(
      vertices = gng_out$nodes$name,
      directed = FALSE
    )

  node_proj <- igraph::layout_with_fr(igr)
  colnames(node_proj) <- c("GNG_X", "GNG_Y")
  rownames(node_proj) <- gng_out$nodes$name

  # Apply minmax-scale
  node_proj <- dynutils::scale_minmax(node_proj)

  # Map the positions to the original space x
  if (!is.null(x)) {
    requireNamespace("randomForestSRC")
    rf <- randomForestSRC::rfsrc(
      formula = Multivar(GNG_X, GNG_Y) ~ .,
      data = data.frame(stats::na.omit(gng_out$node_space), node_proj, check.names = FALSE)
    )
    pred <- stats::predict(rf, data.frame(x, check.names = FALSE, stringsAsFactors = FALSE))
    space_proj <- sapply(colnames(node_proj), function(n) pred$regrOutput[[n]]$predicted)

    rownames(space_proj) <- rownames(x)
  } else {
    space_proj <- NULL
  }

  list(
    node_proj = node_proj,
    space_proj = space_proj,
    igraph = igr
  )
}
