# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib gng
gng_cpp <- function(x, max_iterations, epsilon_b, epsilon_n, age_max, max_nodes, lambda, alpha, beta, verbose) {
    .Call('_gng_gng_cpp', PACKAGE = 'gng', x, max_iterations, epsilon_b, epsilon_n, age_max, max_nodes, lambda, alpha, beta, verbose)
}

